// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4VuqMV880ruBqQSIJZ1Upo3rLLHQ23jY',
    appId: '1:844089529553:web:1bc5cc365561b81f8de1f0',
    messagingSenderId: '844089529553',
    projectId: 'itsd84-quiz-4',
    authDomain: 'itsd84-quiz-4.firebaseapp.com',
    databaseURL: 'https://itsd84-quiz-4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'itsd84-quiz-4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf7qoEm9CIQUstnhdVLeezZb18J4Kw6dc',
    appId: '1:844089529553:android:10b55d82a57139d58de1f0',
    messagingSenderId: '844089529553',
    projectId: 'itsd84-quiz-4',
    databaseURL: 'https://itsd84-quiz-4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'itsd84-quiz-4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO4aXYssV_u9-SZK-GrFh-TFU-JAqQDwo',
    appId: '1:844089529553:ios:373e32a03e3c2a988de1f0',
    messagingSenderId: '844089529553',
    projectId: 'itsd84-quiz-4',
    databaseURL: 'https://itsd84-quiz-4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'itsd84-quiz-4.appspot.com',
    iosBundleId: 'com.example.quiz4Final',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO4aXYssV_u9-SZK-GrFh-TFU-JAqQDwo',
    appId: '1:844089529553:ios:89db696ca7f27db48de1f0',
    messagingSenderId: '844089529553',
    projectId: 'itsd84-quiz-4',
    databaseURL: 'https://itsd84-quiz-4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'itsd84-quiz-4.appspot.com',
    iosBundleId: 'com.example.quiz4Final.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4VuqMV880ruBqQSIJZ1Upo3rLLHQ23jY',
    appId: '1:844089529553:web:224d30d40a3617f08de1f0',
    messagingSenderId: '844089529553',
    projectId: 'itsd84-quiz-4',
    authDomain: 'itsd84-quiz-4.firebaseapp.com',
    databaseURL: 'https://itsd84-quiz-4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'itsd84-quiz-4.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyB4VuqMV880ruBqQSIJZ1Upo3rLLHQ23jY',
    appId: '1:844089529553:web:0bebc74c2f9f45378de1f0',
    messagingSenderId: '844089529553',
    projectId: 'itsd84-quiz-4',
    authDomain: 'itsd84-quiz-4.firebaseapp.com',
    databaseURL: 'https://itsd84-quiz-4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'itsd84-quiz-4.appspot.com',
  );
}
